#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SWARM_HOME = Path(os.environ.get("SWARM_HOME", str(Path.home() / "swarm")))
SWARM_DOCS = SWARM_HOME / "docs"
SNAPSHOT_PATH = SWARM_DOCS / "skill-sync/cli-surface.txt"
HASH_PATH = SWARM_DOCS / "skill-sync/cli-surface.sha256"
CHECKLIST_PATH = SWARM_DOCS / "skill-sync/checklist.md"
DEFAULT_SKILL_PATH = Path.home() / ".codex/skills/forgejoctl/SKILL.md"

BLOCK_START = "<!-- BEGIN FORGEJOCTL_COMMAND_SET -->"
BLOCK_END = "<!-- END FORGEJOCTL_COMMAND_SET -->"

CHECKLIST_ITEMS = (
    "Verified skill command reference against swarm/docs/skill-sync/cli-surface.txt.",
    "Updated skill procedural guidance for any CLI/workflow changes.",
    "Re-ran python3 /home/main/forgejo-agent/scripts/check.py after sync updates.",
)

WORKFLOW_STATES = (
    "triage",
    "spec",
    "ready",
    "in-progress",
    "review",
    "blocked",
)

# Order matters for stable snapshots/hashes.
SURFACE_COMMANDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("forgejoctl --help", ()),
    ("forgejoctl repo --help", ("repo",)),
    ("forgejoctl repo ensure --help", ("repo", "ensure")),
    ("forgejoctl issue --help", ("issue",)),
    ("forgejoctl issue list --help", ("issue", "list")),
    ("forgejoctl issue show --help", ("issue", "show")),
    ("forgejoctl issue create --help", ("issue", "create")),
    ("forgejoctl issue comment --help", ("issue", "comment")),
    ("forgejoctl issue transition --help", ("issue", "transition")),
    ("forgejoctl issue claim --help", ("issue", "claim")),
    ("forgejoctl issue release --help", ("issue", "release")),
    ("forgejoctl issue blocker --help", ("issue", "blocker")),
    ("forgejoctl issue close --help", ("issue", "close")),
    ("forgejoctl issue reopen --help", ("issue", "reopen")),
    ("forgejoctl worker --help", ("worker",)),
    ("forgejoctl worker run --help", ("worker", "run")),
    ("forgejoctl whoami --help", ("whoami",)),
)


def shell(argv: list[str]) -> str:
    proc = subprocess.run(
        argv,
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        print("command failed:", " ".join(argv), file=sys.stderr)
        if proc.stdout:
            print(proc.stdout, file=sys.stderr)
        if proc.stderr:
            print(proc.stderr, file=sys.stderr)
        raise SystemExit(proc.returncode)
    return proc.stdout


def run_help(path: tuple[str, ...]) -> str:
    output = shell(
        ["cargo", "run", "--quiet", "--bin", "forgejo-agent", "--", *path, "--help"]
    )
    return output.rstrip("\n")


def render_snapshot() -> str:
    parts = [
        "# forgejoctl CLI surface snapshot",
        "# Generated by scripts/verify_skill_sync.py --update",
        "",
    ]
    for title, path in SURFACE_COMMANDS:
        parts.append(f"## {title}")
        parts.append("```text")
        parts.append(run_help(path))
        parts.append("```")
        parts.append("")
    return "\n".join(parts)


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def extract_commands(help_text: str) -> list[str]:
    lines = help_text.splitlines()
    inside = False
    commands: list[str] = []
    for line in lines:
        if line.startswith("Commands:"):
            inside = True
            continue
        if not inside:
            continue
        if not line.strip():
            continue
        if line.startswith("Options:") or line.startswith("Arguments:"):
            break
        match = re.match(r"^\s{2}([a-z0-9-]+)\b", line)
        if not match:
            continue
        name = match.group(1)
        if name != "help":
            commands.append(name)
    return commands


def find_block(text: str, start_tag: str, end_tag: str) -> str:
    start = text.find(start_tag)
    end = text.find(end_tag)
    if start < 0 or end < 0 or end <= start:
        raise ValueError(f"missing block markers: {start_tag} ... {end_tag}")
    block_start = start + len(start_tag)
    return text[block_start:end].strip()


def required_command_block() -> str:
    root_help = run_help(())
    issue_help = run_help(("issue",))
    root_commands = " ".join(extract_commands(root_help))
    issue_commands = " ".join(extract_commands(issue_help))
    workflow = " ".join(WORKFLOW_STATES)
    return "\n".join(
        (
            f"root_commands: {root_commands}",
            f"issue_commands: {issue_commands}",
            f"workflow_states: {workflow}",
        )
    )


def update_snapshot() -> None:
    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    snapshot = render_snapshot()
    digest = sha256_hex(snapshot)
    SNAPSHOT_PATH.write_text(snapshot, encoding="utf-8")
    HASH_PATH.write_text(f"{digest}\n", encoding="utf-8")
    print(f"updated snapshot: {SNAPSHOT_PATH}")
    print(f"updated hash: {HASH_PATH}")
    print(f"hash: {digest}")


def check(skill_path: Path) -> None:
    if not SNAPSHOT_PATH.exists() or not HASH_PATH.exists():
        raise SystemExit(
            "missing CLI surface files; run:\n"
            "  python3 scripts/verify_skill_sync.py --update"
        )

    expected_hash = HASH_PATH.read_text(encoding="utf-8").strip()
    if not expected_hash:
        raise SystemExit(f"hash file is empty: {HASH_PATH}")

    snapshot = render_snapshot()
    current_hash = sha256_hex(snapshot)
    if current_hash != expected_hash:
        raise SystemExit(
            "forgejoctl CLI surface changed.\n"
            f"expected hash: {expected_hash}\n"
            f"current  hash: {current_hash}\n"
            "If intended, update snapshot:\n"
            "  python3 scripts/verify_skill_sync.py --update\n"
            "Then update the skill/checklist hash markers."
        )

    if not skill_path.exists():
        raise SystemExit(f"skill file missing: {skill_path}")
    skill_text = skill_path.read_text(encoding="utf-8")
    skill_marker = f"CLI_SURFACE_SHA256: {expected_hash}"
    if skill_marker not in skill_text:
        raise SystemExit(
            "skill hash marker mismatch.\n"
            f"expected marker: {skill_marker}\n"
            f"file: {skill_path}"
        )

    expected_block = required_command_block()
    try:
        actual_block = find_block(skill_text, BLOCK_START, BLOCK_END)
    except ValueError as err:
        raise SystemExit(f"{skill_path}: {err}") from err

    if actual_block != expected_block:
        raise SystemExit(
            "skill command reference block mismatch.\n"
            f"expected:\n{expected_block}\n\n"
            f"actual:\n{actual_block}\n\n"
            "Update the block in the skill file."
        )

    if not CHECKLIST_PATH.exists():
        raise SystemExit(f"checklist missing: {CHECKLIST_PATH}")
    checklist_text = CHECKLIST_PATH.read_text(encoding="utf-8")
    checklist_marker = f"CLI_SURFACE_SHA256: {expected_hash}"
    if checklist_marker not in checklist_text:
        raise SystemExit(
            "checklist hash marker mismatch.\n"
            f"expected marker: {checklist_marker}\n"
            f"file: {CHECKLIST_PATH}"
        )

    for item in CHECKLIST_ITEMS:
        needle = f"- [x] {item}"
        if needle not in checklist_text:
            raise SystemExit(
                "checklist item must be acknowledged before shipping:\n"
                f"{needle}\n"
                f"file: {CHECKLIST_PATH}"
            )

    print("skill/api sync check: OK")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Verify forgejoctl CLI surface is synchronized with skill docs.",
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="Regenerate swarm/docs/skill-sync/cli-surface.txt and cli-surface.sha256",
    )
    parser.add_argument(
        "--skill-path",
        type=Path,
        default=Path(os.environ.get("FORGEJOCTL_SKILL_PATH", DEFAULT_SKILL_PATH)),
        help="Path to skill SKILL.md (default: ~/.codex/skills/forgejoctl/SKILL.md)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.update:
        update_snapshot()
        return
    check(args.skill_path)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit(130)
